data:
  data_folder: './datasets/AgeDB'
  dataset: AgeDB
  aug: 'crop,flip,color,grayscale'


Encoder:
  type: 'resnet18' # resnet50
  trainer:
    epochs: 500
    batch_size: 256
    num_workers: 4
    print_freq: 10
    save_freq: 50
    save_curr_freq: 1
    test_regression_freq: 100
  optimizer:
    learning_rate: 0.2
    lr_decay_rate: 0.1
    weight_decay: 0.0001
    momentum: 0.9

